server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  main:
    banner-mode: off
  cloud:
    discovery:
      enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5430/db_hotel"
    username: "uhotel"
    password: "admin-password-uhotel*"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true