server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  main:
    banner-mode: off
  cloud:
    discovery:
      enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/db_users"
    username: "uuser"
    password: "admin-password-uuser*"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true