services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
        container_name: elasticsearch
        environment:
            - bootstrap.memory_lock=true # Lock the memory to prevent swapping
            - discovery.type=single-node # Run Elasticsearch in single-node mode
            - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set JVM heap size
            - xpack.security.enabled=true # Disable security for simplicity
            - ELASTIC_USERNAME=elastic # Default username
            - ELASTIC_PASSWORD=elastic123 # Default password
        ports:
            - "9200:9200"
        volumes:
            - eslasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:9.2.0
        container_name: kibana
        environment:
            ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpyampmaHZuOVJnaUVvb0VvWG1mQTZB
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        volumes:
          - ./docker-config/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
          - kibana_data:/usr/share/kibana/data
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        networks:
            - elastic
    logstash:
        image: docker.elastic.co/logstash/logstash:9.2.0
        container_name: logstash
        depends_on:
            - elasticsearch
        ports:
            - "5044:5044" # For Beats input
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
          LS_JAVA_OPTS: "-Xmx256m -Xms256m"
          ELASTICSEARCH_USERNAME: elastic
          ELASTICSEARCH_PASSWORD: elastic123
          XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
          XPACK_MONITORING_ELASTICSEARCH_PASSWORD: elastic123
          XPACK_MONITORING_ELASTICSEARCH_HOSTS: 'elasticsearch:9200'
          XPACK_MONITORING_ENABLED: "true"
        volumes:
          - ./docker-config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
          - ./docker-config/logstash/pipeline:/usr/share/logstash/pipeline
        networks:
            - elastic    
    db:
        image: postgres:alpine
        container_name: db
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: default_db
        ports:
            - "5430:5432"
        volumes:
            - ./db-init:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        networks:
            - data_net
    kafka:
        image: apache/kafka:4.1.0  # Usar versión específica
        container_name: kafka      # Usar nombre consistente
        ports:
        - "9092:9092"
        environment:
            # KRaft Configurations
            KAFKA_KRAFT_CLUSTER_ID: "RXnWddkcSMyiJiogkTP6cw"
        
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
            
            # Network Configurations
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

            # Replica/Partition Configurations (your original values are fine for development)
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
    
        # Make sure to include volumes to persist KRaft data
        volumes:
        - kafka_data:/var/lib/kafka/data
        networks:
        - data_net
    api-gateway:
      build: ./api-gateway-service/
      container_name: api-gateway-service
      environment:
        CONFIG_SERVICE_HOST: config-service
        EUREKA_HOST: registration-microservices-service
        LOGSTASH_HOST: logstash
      depends_on:
        - config-service
        - registration-microservices-service
        - logstash
      ports:
        - "8060:8060"
      networks:
        - elastic
        - data_net
    auth-service:
      build: ./auth-service/
      container_name: auth-service
      environment:
        CONFIG_SERVICE_HOST: config-service
        DB_HOST: db
        DB_PORT: 5432
        EUREKA_HOST: registration-microservices-service
        LOGSTASH_HOST: logstash
      depends_on:
        - db
        - kafka
        - config-service
        - registration-microservices-service
        - logstash
      ports:
        - "8070:8070"
      networks:
        - elastic
        - data_net
    hotel-service:
      build: ./hotel-service/
      container_name: hotel-service
      environment:
        DB_HOST: db
        DB_PORT: 5432
        EUREKA_HOST: registration-microservices-service
        CONFIG_SERVICE_HOST: config-service
        LOGSTASH_HOST: logstash
      depends_on:
        - db
        - kafka
        - config-service
        - registration-microservices-service
        - logstash
      ports:
        - "8082:8082"
      networks:
        - elastic
        - data_net
    payment-service:
      build: ./payment-service/
      container_name: payment-service
      environment:
        DB_HOST: db
        DB_PORT: 5432
        EUREKA_HOST: registration-microservices-service
        CONFIG_SERVICE_HOST: config-service
        LOGSTASH_HOST: logstash
      depends_on:
        - db
        - kafka
        - config-service
        - registration-microservices-service
        - logstash
      ports:
        - "8083:8083"
      networks:
        - elastic
        - data_net
    user-service:
      build: ./user-service/
      container_name: user-service
      environment:
        DB_HOST: db
        DB_PORT: 5432
        EUREKA_HOST: registration-microservices-service
        CONFIG_SERVICE_HOST: config-service
        LOGSTASH_HOST: logstash
      depends_on:
        - db
        - kafka
        - config-service
        - registration-microservices-service
        - logstash
      ports:
        - "8081:8081"
      networks:
        - elastic
        - data_net
    registration-microservices-service:
      build: ./registration-microservices-service/
      container_name: registration-microservices-service
      environment:
        SERVICE_HOST: registration-microservices-service
      ports:
        - "8761:8761"
      networks:
        - data_net
    config-service:
      build: ./config-service/
      container_name: config-service
      environment:
        EUREKA_HOST: registration-microservices-service
        LOGSTASH_HOST: logstash
      depends_on:
        - registration-microservices-service
      ports:
        - "8088:8088"
      volumes:
        - ./config-service/src/main/resources/config:/app/src/main/resources/config # Permite que no tenga que recrear la imagen completa del servicio para hacer valida las configuraciones de otros microservicios
      networks:
        - elastic
        - data_net
volumes:
    eslasticsearch_data:
        driver: local
    postgres_data:
        driver: local
    kafka_data:
        driver: local
    kibana_data:
        driver: local
networks:
    elastic:
        driver: bridge
    data_net:
        driver: bridge
        