# logstash.conf
input {
  # 1. Input para recibir logs de Spring Boot a través de TCP/UDP
  tcp {
    port => 5000
    codec => json
  }
}
output {
  # 2. Output para enviar los datos a Elasticsearch
  elasticsearch {
    hosts => "elasticsearch:9200" # Conexión a través de la red Docker
    index => "Hotel-app-logs-%{+YYYY.MM.dd}" # Nombre del índice en ES
    user => "elastic"
    password => "elastic123"
    ssl_enabled => false # Asumimos que no estás usando SSL/HTTPS internamente
  }
}