input {
  tcp {
    port => 5000
    codec => json
  }
}
output {
  elasticsearch {
    hosts => "elasticsearch:9200"
    index => "hotel-app-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "elastic123"
    ssl_enabled => false
  }
}